---
title: "The best of both worlds (R and Python)"
author: "Joaquin Moreno"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

#Blog

After developing an understanding of how to use R-studio in my Computational Biology course this semester, my peers and I had the opportunity of combining R with Python. Python is a well-known computing language, but can also be used effectively for data science purposes and computational biology.

In this post, I will show how Python code can actually be used inside an R script after installing some packages.

Follow along!

You first want to make sure you install the necessary packages in R. For the purpose of this blog, we will use the R reticulate package.


This package allows you to run Python code within an R script in order to remain connected between the two coding languages/platforms.

Next, we will walk through an example that uses Python code to create an array of four numbers:

